# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About me"
  url = "#about"
  weight = 10

[[main]]

  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
 name = "Awards"
 url = "#accomplishments"
 weight = 40

[[main]]
  name = "Work"
  url = "#experience"
  weight = 50

[[main]]
  name = "Blog"
  url = "/post/"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

